GET http://localhost:8888/graphsupply
###
GET http://localhost:8888/graphsupply/last
###
GET http://localhost:8888/graphsupply/static/urxn.txt
###
GET http://localhost:8888/graphsupply/static/bundle.js
###
GET http://localhost:8888/graphsupply/static/johndoe.png
###
GET http://localhost:8888/graphsupply/static/css.css
###
POST http://localhost:8888/graphsupply/random
Content-Type: application/json

{"density": 80, "nodes": 5, "weighted": true}
###
POST http://localhost:8888/graphsupply/random
Content-Type: application/json

{"density": 50, "nodes": 7, "weighted": true}
###
GET http://localhost:8888/graphsupply

###
GET http://localhost:8888/graphsupply/random?nodes=5&density=100

###
GET http://localhost:8888/graphsupply/random?nodes=3&loops=true&density=99&weighted=r
